import Head from 'next/head';
import { useState } from 'react';

export default function Home() {
  const [vizQuery, setVizQuery] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    setVizQuery('');
    console.log('submitted!');
  };

  return (
    <div className="flex justify-center items-center flex-col p-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-gray-200 text-5xl">
        Natural Language to Visualization Survey and Benchmarks
      </h1>
      <p className="text-gray-100 ">
        This is a website that serves as an end-to-end system for benchmarking
        natural language to visualization systems.
      </p>

      <span>
        <h3 className="text-gray-200 text-lg">
          Enter what you want to vizualize.
        </h3>

        <form action="" onSubmit={handleSubmit}>
          <input
            className="w-96 pb-1 pr-1 mr-1 bg-transparent border-b-2 border-yellow-500  focus:border-gray-100 focus:outline-none transition-colors duration-300"
            type="text"
            name="Vizualization query"
            id=""
            value={vizQuery}
            onChange={(e) => setVizQuery(e.target.value)}
          />
          <button className="p-2 rounded-md bg-gradient-to-tr from-yellow-500 bg-yellow-700 hover:bg-yellow-500 hover:scale-105 transition-all">
            Submit Query
          </button>
        </form>
      </span>
      {vizQuery}
    </div>
  );
}
